// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYDWgN9ledhEuoaqb2vqM9M6-e9gSuEQ',
    appId: '1:614465630907:web:356dcf432c26bb17d66f9e',
    messagingSenderId: '614465630907',
    projectId: 'twalitso',
    authDomain: 'twalitso.firebaseapp.com',
    storageBucket: 'twalitso.firebasestorage.app',
    measurementId: 'G-WECSRNPQGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNYpgfqcEjqYO5BLcZL3yqJi0x6ETghVY',
    appId: '1:614465630907:android:7cc02eceab7506bbd66f9e',
    messagingSenderId: '614465630907',
    projectId: 'twalitso',
    storageBucket: 'twalitso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcjey8YZqG5nyDYs47_4OSd9H9MNTX-z8',
    appId: '1:614465630907:ios:f71ee7a40cec2459d66f9e',
    messagingSenderId: '614465630907',
    projectId: 'twalitso',
    storageBucket: 'twalitso.firebasestorage.app',
    iosBundleId: 'com.twalitso.padue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcjey8YZqG5nyDYs47_4OSd9H9MNTX-z8',
    appId: '1:614465630907:ios:f71ee7a40cec2459d66f9e',
    messagingSenderId: '614465630907',
    projectId: 'twalitso',
    storageBucket: 'twalitso.firebasestorage.app',
    iosBundleId: 'com.twalitso.padue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRYDWgN9ledhEuoaqb2vqM9M6-e9gSuEQ',
    appId: '1:614465630907:web:685389e668f273f0d66f9e',
    messagingSenderId: '614465630907',
    projectId: 'twalitso',
    authDomain: 'twalitso.firebaseapp.com',
    storageBucket: 'twalitso.firebasestorage.app',
    measurementId: 'G-1H3HQJH21Q',
  );
}
